client_script "@vrp/lib/lib.lua" --Para remover esta pendencia de todos scripts, execute no console o comando "uninstall"

fx_version 'bodacious'
games { 'gta5' }

author 'Pequi Shop'
description 'Script for phone'
version '1.1.9'

ui_page "html/index.html"

shared_scripts {
    "config.lua",
    "locale.lua",
    "locales/br.lua",
    "locales/en.lua",
}

client_scripts {
	"@vrp/lib/utils.lua",
	'locale.lua',
    "locales/br.lua",
    "locales/en.lua",
    'client/animation.lua',
    'client/cl_main.lua',
    'client/photo.lua',
    'client/variables.lua',
}

server_scripts {
	"@vrp/lib/utils.lua",
	'locale.lua',
    "locales/br.lua",
    "locales/en.lua",
	"system/functions.lua",
    'server/functions.lua',
    'server/sv_main.lua',
}

files {
    'html/index.html',
    'html/css/audio.css',
    'html/css/bank.css',
    'html/css/calculator.css',
    'html/css/camera.css',
    'html/css/darkweb.css',
    'html/css/fonts.css',
    'html/css/gallery.css',
    'html/css/help.css',
    'html/css/instagram.css',
    'html/css/instagram-filters.min.css',
    'html/css/main.css',
    'html/css/messages.css',
    'html/css/news.css',
    'html/css/olx.css',
    'html/css/painel.css',
    'html/css/phone.css',
    'html/css/settings.css',
    'html/css/slither.css',
    'html/css/spotify.css',
    'html/css/stories.css',
    'html/css/tinder.css',
    'html/css/tooltip.css',
    'html/css/truco.css',
    'html/css/twitter.css',
    'html/css/whatsapp.css',
    'html/fonts/Azonix.otf',
    'html/fonts/font-1.ttf',
    'html/fonts/HelveticaNeue-Medium.ttf',
    'html/fonts/keepcalm.otf',
    'html/fonts/KeepCalm-Medium.ttf',
    'html/fonts/SamsungSans-Bold.woff',
    'html/fonts/SamsungSans-Light.woff',
    'html/fonts/SamsungSans-Medium.woff',
    'html/fonts/SamsungSans-Regular.woff',
    'html/fonts/SamsungSans-Thin.woff',
    'html/fonts/SFProDisplay-Bold.ttf',
    'html/fonts/SFProDisplay-Regular.ttf',
    'html/fonts/sf-pro-text-bold.woff',
    'html/fonts/sf-pro-text-light.woff',
    'html/fonts/sf-pro-text-medium.woff',
    'html/fonts/sf-pro-text-regular.woff',
    'html/fonts/sf-pro-text-semibold.woff',
    'html/img/apps/bank.png',
    'html/img/apps/chatswppiphone.png',
    'html/img/apps/configwppiphone.png',
    'html/img/apps/creatgroup.png',
    'html/img/apps/groupwppiphone.svg',
    'html/img/apps/information.png',
    'html/img/apps/instagram.png',
    'html/img/apps/instagram-verify.png',
    'html/img/apps/logintinder.png',
    'html/img/apps/map.png',
    'html/img/apps/pequibank.png',
    'html/img/apps/pequipag.png',
    'html/img/apps/tinder.jpg',
    'html/img/apps/tinderlogo.png',
    'html/img/apps/tinderlogo2.png',
    'html/img/apps/twitter.png',
    'html/img/apps/twitter-white.png',
    'html/img/apps/whatsapp-chat.png',
    'html/img/apps/wpp1.png',
    'html/img/apps/wpp-create-account.png',
    'html/img/backgrounds/background.jpg',
    'html/img/icons/anonima.png',
    'html/img/icons/apple.png',
    'html/img/icons/back1.png',
    'html/img/icons/background.png',
    'html/img/icons/banco.png',
    'html/img/icons/banco-bkp.png',
    'html/img/icons/calculadora.png',
    'html/img/icons/camera.png',
    'html/img/icons/configuracoes.png',
    'html/img/icons/gallery.png',
    'html/img/icons/help.png',
    'html/img/icons/instagram.png',
    'html/img/icons/messages.png',
    'html/img/icons/noticias.png',
    'html/img/icons/olx.png',
    'html/img/icons/photos.png',
    'html/img/icons/slither.png',
    'html/img/icons/spotify.png',
    'html/img/icons/telefone.png',
    'html/img/icons/tinder.png',
    'html/img/icons/tor.png',
    'html/img/icons/truco.png',
    'html/img/icons/twitter.png',
    'html/img/icons/whatsapp.png',
    'html/img/icons/zoom.png',
    'html/img/navigation/center.png',
    'html/img/navigation/left.png',
    'html/img/navigation/right.png',
    'html/img/cloud.png',
    'html/img/default.png',
    'html/img/default-cover.jpg',
    'html/img/xs.png',
    'html/js/app.js',
    'html/js/audio.js',
    'html/js/bank.js',
    'html/js/calculator.js',
    'html/js/camera.js',
    'html/js/config.js',
    'html/js/darkweb.js',
    'html/js/gallery.js',
    'html/js/help.js',
    'html/js/instagram.js',
    'html/js/messages.js',
    'html/js/news.js',
    'html/js/olx.js',
    'html/js/painel.js',
    'html/js/phone.js',
    'html/js/settings.js',
    'html/js/slither.js',
    'html/js/spotify.js',
    'html/js/stories.js',
    'html/js/tinder.js',
    'html/js/truco.js',
    'html/js/twitter.js',
    'html/js/whatsapp.js',
    'html/sound/Phone_Call_Sound_Effect.ogg',
    'html/sound/ring.ogg',
    'html/sound/tchatNotification.ogg',
    'html/sound/Twitter_Sound_Effect.ogg',
}

dependencies {
    'vrp',
    'oxmysql'
}              